apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/xinredhat/rust-builder?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "tc-5149-xjiangplnsvc-tenant"
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: rust-builder
    appstudio.openshift.io/component: rust-builder-ubi10
    pipelines.appstudio.openshift.io/type: build
  name: rust-builder-ubi10-on-push
  namespace: xjiangplnsvc-tenant
spec:
  pipelineRef:
    name: rust-builder-pipeline
  timeouts:
    pipeline: 96h
    tasks: 96h
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/xjiangplnsvc-tenant/rust-builder/rust-builder-ubi10:{{revision}}
  - name: build-platforms
    value:
    - linux-d160-m8xlarge/amd64
    - linux-d160-m8xlarge/arm64
    - linux/ppc64le
    - linux/s390x
  - name: dockerfile
    value: Containerfile.ubi10
  - name: hermetic
    value: 'true'
  - name: prefetch-input
    value: |
      [
        {
          "type": "generic",
          "path": "."
        },
        {
          "type": "rpm",
          "path": "ubi10"
        }
      ]
  - name: build-source-image
    value: "true"
  taskRunTemplate:
    serviceAccountName: build-pipeline-rust-builder-ubi10
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
